### PR TITLE
use es6 syntax, fix kayla-tech/react-native-card-io#17, support RN 25

### PR DESCRIPTION
**Pull request by sibelius**

### CODE REVIEW

**Comment by rturk** [comment]
@sibeliusseraphini tks! I was about to write some code to port this

@rogchap can you review this, merge and publish a new major version? Tks!

**Comment by rogchap** [comment]
Great call. thank @sibeliusseraphini @rturk

**Comment by rogchap** [comment]
@rturk I'm having issues with publishing to npm.

The issues seem to be with npm itself (PUT command returning 503).
Will try again (and again) and let you know when it's published.

Might be due to my slow upload speed (working from home this week).

**Comment by rogchap** [comment]
Finally managed to publish 1.0.5 to NPM Registry.

**Pull request merged**
